Graphs displaying data dynamically in widgets
OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa pull request #133
Opened 2024-11-05 05:22 UTC by BenCampbellNelson

Overhaul of graph components with more dynamic y axis and x axis. 

Ability to scroll across graph on mobile view to prevent squishing!

All common logic between graph components moved to chartUtils.js 

Create variables for ease if need to change style and colouring of site. Buttons can be subject to change as well

2024-11-05 22:00 UTC, SamanthaCra requested changes
We'll need to increase the requests or find a way to disable the graphs being requests of their own. Looking through all of the different graphs just tanks the request limit.

2024-11-05 22:03 UTC, SamanthaCra commented
Can we add buttons to display the graphs?

2024-11-05 22:20 UTC, BenCampbellNelson commented on fullstack/src/app/page.js
> +        <Widget name="CO2" dataKey="co2" GraphComponent={BarChartComponent} />
Weird I didn't notice that, they were hourly

2024-11-06 22:20 UTC, SamanthaCra commented on fullstack/src/app/page.js
> +        <Widget name="CO2" dataKey="co2" GraphComponent={BarChartComponent} />
![image](https://github.com/user-attachments/assets/b46f5351-3dea-41e5-b173-49ff8c15cc45)
Thanks for the fix :)

2024-11-06 22:45 UTC, SamanthaCra approved these changes
Awesome changes, looks really good. Nice friendly UI, responsive, good commenting and well thought out.

2024-11-06 22:45 UTC, SamanthaCra commented on fullstack/src/components/graphs/LineChartComponent.jsx
Nice and responsive

2024-11-07 01:41 UTC, merged