Cloud  GUI
OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa pull request #135
Opened 2024-11-06 08:39 UTC by TomMc608

This is the front end connect to the app to use the cloud image AI that is being hosed on hugging face.

2024-11-06 21:59 UTC, SamanthaCra commented
@TomMc608 can you please give instructions for how we are meant to run and test this?

2024-11-06 22:29 UTC, TomMc608 commented
> @TomMc608 can you please give instructions for how we are meant to run and test this?

Added the read me

2024-11-06 23:21 UTC, SamanthaCra requested changes
A few changes to think about.

2024-11-06 23:21 UTC, SamanthaCra commented on fullstack/src/app/cloud-details/PythonBackEnd/Dockerfile
Can we move this to the fullstack dir and give it a .cloud extention or something? Also give the existing one a .web or .app extension

2024-11-06 23:21 UTC, SamanthaCra commented on fullstack/src/app/cloud-details/PythonBackEnd/app.py
can we change the PythonBackEnd dir to python-backend for consistency please?

2024-11-06 23:21 UTC, SamanthaCra commented on fullstack/src/app/cloud-details/ReadMe
Can we change the name to README.md for consistency please.

2024-11-06 23:21 UTC, SamanthaCra commented on fullstack/src/app/cloud-details/ReadMe
> +    fastapi-app`
might want to change this to a single line for consistency

2024-11-06 23:21 UTC, SamanthaCra commented on fullstack/src/app/cloud-details/page.js
> +const CloudDetails = () => {
This should be changed to export default function CloudDetails() {

2024-11-06 23:21 UTC, SamanthaCra commented on fullstack/src/app/cloud-details/page.js
> +export default CloudDetails;
See earlier comment, this can be removed

2024-11-06 23:21 UTC, SamanthaCra commented on fullstack/src/app/cloud-details/page.js
This should be split into a page and the component should be moved into components. 
```
'use client';
import Cloud from "@/components/cloud";

export default function CloudDetails() {
  return (
    <div className="app-container">
      <Cloud />
    </div>
  );
}
```

2024-11-06 23:21 UTC, SamanthaCra commented on fullstack/src/app/cloud-details/page.js
src/app/components/cloud.jsx
```
import React, { useState } from 'react';

const CloudDetails = () => {
const [result, setResult] = useState(''); 
const [loading, setLoading] = useState(false);
const images = [
    { id: 1, src: '/images/1.png', alt: 'Cloud Image 1' },
  ];

  const handleImageClick = async (imageSrc) => {
    try {
      setLoading(true);

      const response = await fetch(imageSrc); 
      const imageBlob = await response.blob(); 

      const formData = new FormData();
      formData.append('image', imageBlob, 'uploaded_image.jpg');

      // Send the image to Python 
      const apiResponse = await fetch('http://localhost:8000/analyze', {
        method: 'POST',
        body: formData,
      });

      const resultData = await apiResponse.json(); 

      setResult(resultData.result); 
    } catch (error) {
      console.error('Error:', error);
      setResult('Error occurred during prediction.');
    } finally {
      setLoading(false); 
    }
  };
  return (
    <div className="min-h-screen bg-[--color-background] text-[--foreground] flex flex-col items-center py-10">
      <h1 className="text-3xl font-bold mb-4">Cloud Details</h1>
      <p className="text-lg mb-6">Select an image to analyze:</p>

      <div className="flex gap-4 flex-wrap justify-center mb-6">
        {images.map((image) => (
          <img
            key={image.id}
            src={image.src}
            alt={image.alt}
            className="w-36 h-36 rounded-lg cursor-pointer transition-transform duration-300 hover:scale-110 hover:shadow-lg"
            onClick={() => handleImageClick(image.src)} 
          />
        ))}
      </div>

      {loading && <p className="text-lg text-[--secondary-foreground]">Analyzing image...</p>}

      {result && (
        <div className="mt-6 p-4 bg-white text-[--foreground] rounded-md shadow-md">
          <h3 className="text-xl font-semibold mb-2">Prediction Result:</h3>
          <pre className="text-sm">{result}</pre>
        </div>
      )}
    </div>
  );
};

export default CloudDetails;
```

2024-11-06 23:21 UTC, SamanthaCra commented on fullstack/src/app/page.js
TBC with Ben/UI update

2024-11-06 23:31 UTC, SamanthaCra reviewed
![image](https://github.com/user-attachments/assets/eb903caa-409f-4d2f-ae07-c1a394644cd2)
Currently impossible to read. Upload works fine, throbber is a good addition.

2024-11-06 23:31 UTC, SamanthaCra commented on fullstack/src/app/cloud-details/PythonBackEnd/app.py
> +        raise HTTPException(status_code=400, detail="Only JPEG and PNG images are supported.")
Can this allow HEIC?

2024-11-06 23:31 UTC, SamanthaCra commented
PythonBackEnd can be moved to src/

2024-11-07 00:53 UTC, SamanthaCra approved these changes
Well done

2024-11-07 01:36 UTC, merged