Nextjs switch
OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa pull request #76
Opened 2024-09-08 03:08 UTC by fuzzyers

I have merged the back and frontend into a single fullstack NEXTJS

2024-09-08 04:28 UTC, SamanthaCra requested changes
Great job, dev runs well and everything is still nice and responsive.  I will have to sit down with you to ensure the build is working as I received an error. We use the build on the app.

Also the favicon and title are gone, they were in the app Ben built. 

Build error:
```Build error occurred
Error: Failed to collect page data for /api/recieve-data
    at D:\skool\Cloudy-with-a-Chance-of-LoRa\fullstack\node_modules\next\dist\build\utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}````

2024-09-08 04:28 UTC, SamanthaCra commented on fullstack/src/app/api/recieve-data/route.js
Will communicate the schema to you this week to ensure this works with the Postgres database.

2024-09-08 05:26 UTC, fuzzyers commented
> Great job, dev runs well and everything is still nice and responsive. We want to ensure the build is working as I received an error. We use the build on the application server.
> 
> Also the favicon and title are gone, they were in the app Ben built.
> 
> Build error:
> 
> ```
> Error: Failed to collect page data for /api/recieve-data
>     at D:\skool\Cloudy-with-a-Chance-of-LoRa\fullstack\node_modules\next\dist\build\utils.js:1268:15
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   type: 'Error'
> }````
> ```


So the build Error seems to be related to the missing .env file and a database link as it cant compile the API so this wont be an issue in the proper build as we will have the .env in it I have also updated the backend wiki to talk about the setup process of this.

The favicon and title have been readded

2024-09-08 20:12 UTC, SamanthaCra approved these changes
Thanks for updating that and letting me know how the error can be fixed. I will look into updating Docker today.

2024-09-08 20:13 UTC, SamanthaCra commented
You should be able to delete that Dockerfile if it's creating conflicts.

2024-09-09 01:50 UTC, BenCampbellNelson approved these changes
Great idea switching us over to Next.js. This decision is going to be great for the scalability of the project for the future and makes it a lot easier for routing and using the API.

2024-09-09 02:04 UTC, merged