Widgets expanding to show graphs with fake data
OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa pull request #93
Opened 2024-09-19 08:50 UTC by BenCampbellNelson

Added ability to expand widgets to display shadcn graphs. Have installed tailwind and shadcn to achieve this functionality. There is some dummy data hard coded in there that has been used so I could get the tables up and going for display and prototyping purposes. Next step is displaying the dust data that we are now receiving!

2024-09-23 02:24 UTC, fuzzyers commented on fullstack/src/app/page.js
Container component isnt really needed its just excessive over head since it takes up the whole page.
Try keep in mind how you put something together to avoid excessive files

2024-09-23 02:25 UTC, fuzzyers commented on fullstack/src/components/container.jsx
> +const temperatureData = [
Good job setting up data as props this will likely be the way we want to parse real data

2024-09-23 02:27 UTC, fuzzyers commented on fullstack/src/components/ui/chart.jsx
> +
This file could use with some formatting

2024-09-23 02:46 UTC, fuzzyers approved these changes
Looks good we need to decide on how we want to format each widgets graphs

2024-09-23 03:26 UTC, SamanthaCra commented
Recieved feedback that you get lost on the page when opening a graph.
Also that the graphs should be consistent/have the option to show monthly/daily/weekly (Understand we don't have the data now - possibly  a future idea)

2024-09-23 03:26 UTC, SamanthaCra commented
Temperature and pressure could be capitilised? 
![image](https://github.com/user-attachments/assets/9ae40f45-85b0-4522-bd5d-6d4f2c8370f9)

2024-09-23 03:27 UTC, SamanthaCra commented
Spacing on the temperature graph doesn't quite hold every day of the week and the numbers on the left are a bit confusing on how they jump - maybe switch it to 5's going up to 35?
![image](https://github.com/user-attachments/assets/c0bff6f6-f701-4e2f-8822-4bbde8f6b209)

2024-09-23 03:55 UTC, SamanthaCra requested changes
Nice work overall, just a few UX issues that jumped out at me.

2024-09-23 03:55 UTC, SamanthaCra commented on fullstack/src/app/OP-logo.png
Cloudy-with-a-Chance-of-LoRa\fullstack\src\app\favicon.ico will need deleted or replaced in order for this to show.

2024-09-23 03:55 UTC, SamanthaCra commented on fullstack/src/app/page.css
> +  .widgets {
These containers aren't mobile-friendly anymore :(

2024-09-23 03:55 UTC, SamanthaCra commented on fullstack/src/components/graphs/LineChartComponent.jsx
> +
This doesn't fit the days of the week in it comfortably.

2024-09-25 05:04 UTC, BenCampbellNelson commented on fullstack/src/app/page.js
All good! I think you may have done that during the next.js switch. Thought there may have been a reason but can fix that issue quite easily!

2024-09-25 22:27 UTC, SamanthaCra approved these changes
Thanks for the fixes, this is looking really nice.

2024-09-25 22:27 UTC, SamanthaCra commented on fullstack/src/components/graphs/BarChartComponent.jsx
Awesome, charts are really nice to look at and understand!

2024-09-25 23:37 UTC, SamanthaCra reviewed
Nice changes, just adding the comments we had about background here
Current: 
![image](https://github.com/user-attachments/assets/d3a03b3d-69dc-4171-a3ec-e266303c0f3f)
Possible change to 4fb5dd:
![image](https://github.com/user-attachments/assets/8cff2fe1-cb4e-4ff2-9577-a3732f436167)

2024-09-25 23:47 UTC, SamanthaCra commented on fullstack/src/app/OP-logo.png
Fixed

2024-09-26 00:05 UTC, BenCampbellNelson commented
* Short term fix for users getting lost when graph is open. Have made the button visible when widget is expanded. In future thinking of making the widget itself a button so users can just click the widget for expansion and for closing, will negate users getting lost trying to find it at all.  
* Days of the week convert to their first letter on mobile view for easier viewing.
* Y-axis is now dynamic depending on the data they receive as well so graphs are fully dynamic components for use with other data in the future.
* Change to a darker colour was a great shout. Has been implemented. In future I will return to the idea of a dynamic background depending on weather/time. For now this is great.
![image](https://github.com/user-attachments/assets/9795803d-27a7-411a-b289-f1298bfb62b4)

2024-09-26 02:35 UTC, merged